apiVersion: v1
kind: Service
metadata:
  name: eventstore-service
spec:
  type: ClusterIP
  selector:
    app: eventstore
  ports:
    - name: ext-tcp-port
      protocol: TCP
      port: 1113
      targetPort: 1113
    - name: ext-http-port
      protocol: TCP
      port: 2113
      targetPort: 2113
