---
env:
  contexts:
    - name: 'simple-json'
      urls:
        - 'https://goalie.mp.exclaimertest.net'
      includePaths:
        - 'https://goalie.mp.exclaimertest.net/.*'
      excludePaths: []
      authentication:
        method: 'browser'
        parameters:
          loginPageUrl: 'https://goalie.mp.exclaimertest.net'
          loginPageWait: 2
          browserId: 'chrome-headless'
        verification:
          method: 'poll'
      sessionManagement:
        method: 'autodetect'
        parameters: {}
      technology:
        exclude: []
      users:
        - name: 'test'
          credentials:
            username: 'zaproxy'
            password: 'zaproxy'
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
  # - parameters:
  #     maxAlertsPerRule: 0
  #     scanOnlyInScope: true
  #     maxBodySizeInBytesToScan: 0
  #     enableTags: false
  #     disableAllRules: true
  #   rules:
  #     - id: 10111
  #       name: 'Authentication Request Identified'
  #       threshold: 'medium'
  #     - id: 10112
  #       name: 'Session Management Response Identified'
  #       threshold: 'medium'
  #     - id: 10113
  #       name: 'Verification Request Identified'
  #       threshold: 'medium'
  #   name: 'passiveScan-config'
  #   type: 'passiveScan-config'
  - parameters:
      user: 'test'
    requests:
      - url: 'https://goalie.mp.exclaimertest.net'
        name: ''
        method: ''
        httpVersion: ''
        headers: []
        data: ''
    name: 'requestor'
    type: 'requestor'
    tests:
      - type: 'stats'
        statistic: 'stats.auth.success'
        site: 'https://goalie.mp.exclaimertest.net'
        operator: '>='
        value: 1
        onFail: 'error'
      - type: 'stats'
        statistic: 'stats.auth.state.loggedin'
        site: 'https://goalie.mp.exclaimertest.net'
        operator: '>='
        value: 1
        onFail: 'error'
      - type: 'stats'
        statistic: 'stats.auth.sessiontoken.accesstoken'
        site: 'https://goalie.mp.exclaimertest.net'
        operator: '>='
        value: 1
        onFail: 'error'
      - type: 'stats'
        statistic: 'stats.auth.configure.session.header'
        operator: '>='
        value: 1
        onFail: 'error'
      - type: 'stats'
        statistic: 'stats.auth.detect.auth.json'
        operator: '>='
        value: 1
        onFail: 'error'
