apiVersion: v1
kind: Service
metadata:
  name: nats-service
spec:
  type: ClusterIP
  selector:
    app: nats
  ports:
    - name: http-port
      protocol: TCP
      port: 4222
      targetPort: 4222
