/**
 * api-gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { CreateGoalDto, Goal, GoalActivity } from '../model/models';

import { Configuration } from '../configuration';

export interface GoalsServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Delete a goal for a user.
   *
   * @param id
   */
  _delete(id: string, extraHttpRequestParams?: any): Observable<{}>;

  /**
   * Complete a goal for a user.
   *
   * @param id
   */
  complete(id: string, extraHttpRequestParams?: any): Observable<{}>;

  /**
   * Create a new goal.
   *
   * @param createGoalDto
   */
  create(createGoalDto: CreateGoalDto, extraHttpRequestParams?: any): Observable<string>;

  /**
   * Get a goal for a user.
   *
   * @param id
   */
  get(id: string, extraHttpRequestParams?: any): Observable<Goal>;

  /**
   * Get a goal activity for a user.
   *
   * @param id
   */
  getActivity(id: string, extraHttpRequestParams?: any): Observable<Array<GoalActivity>>;

  /**
   * Get all goals for a user.
   *
   */
  getAll(extraHttpRequestParams?: any): Observable<Array<Goal>>;

  /**
   *
   *
   * @param userId
   */
  getUsersGoals(userId: string, extraHttpRequestParams?: any): Observable<Array<Goal>>;
}
