apiVersion: v1
kind: Service
metadata:
  name: users-service-service
spec:
  type: ClusterIP
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http-port
