/**
 * oauth-agent-service
 * oauth-agent-service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Check200ResponseInfoValue } from './check200-response-info-value';

export interface Check200Response {
  status?: string;
  info?: { [key: string]: Check200ResponseInfoValue } | null;
  error?: { [key: string]: Check200ResponseInfoValue } | null;
  details?: { [key: string]: Check200ResponseInfoValue };
}
