# Custom values for Curity Identity Server Helm Chart.
# Please refer to https://github.com/curityio/idsvr-helm/blob/master/idsvr/README.md for exhaustive set of configuration options.
#
# -----------------------------------------------------------------------------
# Deployment parameters
# -----------------------------------------------------------------------------

curity:
  config:
    uiEnabled: true
    backup: true
    configuration:
      - secretRef:
          name: idsvr-config
          items:
            - key: license.json
              path: license/license.json
    configurationSecret: idsvr-config
    configurationSecretItemName: idsvr-cluster-config.xml

  admin:
    logging:
      level: DEBUG

  runtime:
    logging:
      level: DEBUG

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
  runtime:
    enabled: true
    host: login.mp.exclaimertest.net
    secretName: login-aks-tls
    paths:
      - /
  admin:
    enabled: true
    host: admin.mp.exclaimertest.net
    secretName: admin-aks-tls
