/**
 * api-gateway
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateGoalDto {
  /**
   * The user ID.
   */
  userId: string;
  /**
   * The name of the goal.
   */
  name: string;
  /**
   * The target number of times to complete the goal.
   */
  target: number;
}
