apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-agent-service
spec:
  selector:
    matchLabels:
      app: oauth-agent-service
  template:
    metadata:
      labels:
        app: oauth-agent-service
    spec:
      containers:
        - name: oauth-agent-service
          {{- if .Values.image.full }}
          image: {{ .Values.image.full }}
          {{- else }}
          image: goalie.azurecr.io/oauth-agent-service:{{ .Values.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLIENT_ID
              value: 'spa-client'
            - name: CLIENT_SECRET
              value: '{{ .Values.clientSecret }}'
            - name: REDIRECT_URI
              value: 'https://goalie.mp.exclaimertest.net'
            - name: POST_LOGOUT_REDIRECT_URI
              value: 'https://goalie.mp.exclaimertest.net'
            - name: COOKIE_NAME_PREFIX
              value: 'goalie'
            - name: COOKIE_ENCRYPTION_KEY
              value: '{{ .Values.cookieEncryptionKey }}'
            - name: CORS_ENABLED
              value: 'true'
            - name: TRUSTED_WEB_ORIGIN
              value: 'https://goalie.mp.exclaimertest.net'
            - name: COOKIE_DOMAIN
              value: 'mp.exclaimertest.net'
            - name: ISSUER
              value: 'https://login.mp.exclaimertest.net/oauth/v2/oauth-anonymous'
            - name: AUTHORIZE_ENDPOINT
              value: 'https://login.mp.exclaimertest.net/oauth/v2/oauth-authorize'
            - name: LOGOUT_ENDPOINT
              value: 'https://login.mp.exclaimertest.net/oauth/v2/oauth-session/logout'
            - name: TOKEN_ENDPOINT
              value: 'https://login.mp.exclaimertest.net/oauth/v2/oauth-token'
            - name: USERINFO_ENDPOINT
              value: 'https://login.mp.exclaimertest.net/oauth/v2/oauth-userinfo'
            - name: TRACING_ENABLED
              value: 'false'
            - name: TRACING_CONSOLE_EXPORTER
              value: 'false'
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 4
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 4
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 2
