/**
 * oauth-agent-service
 * oauth-agent-service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { LoginEndDto, LoginEndResponse, LoginStartDto, LoginStartResponse } from '../model/models';

import { Configuration } from '../configuration';

export interface LoginServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Get the CSRF token.
   *
   */
  getCsrfToken(extraHttpRequestParams?: any): Observable<string>;

  /**
   * End the login process.
   *
   * @param loginEndDto
   */
  loginEnd(loginEndDto: LoginEndDto, extraHttpRequestParams?: any): Observable<LoginEndResponse>;

  /**
   * Start the login process.
   *
   * @param loginStartDto
   */
  loginStart(loginStartDto: LoginStartDto, extraHttpRequestParams?: any): Observable<LoginStartResponse>;
}
