/**
 * oauth-agent-service
 * oauth-agent-service
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { Configuration } from '../configuration';

export interface UserInfoServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Get the user info.
   *
   */
  getUserInfo(extraHttpRequestParams?: any): Observable<{ [key: string]: any }>;
}
