name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: ['main']
    # Publish semver tags as releases.
    tags: ['v*.*.*']
  pull_request:
    branches: ['main']

env:
  REGISTRY: goalie.azurecr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry except on PR
      - name: Azure Container Registry Login
        if: github.event_name != 'pull_request'
        uses: Azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build
        run: |
          yarn install

          yarn nx build api-gateway
          docker build -f apps/api-gateway/Dockerfile . -t ${{ env.REGISTRY }}/api-gateway:latest
          docker push ${{ env.REGISTRY }}/api-gateway:latest

          yarn nx build oauth-agent-service
          docker build -f apps/services/oauth-agent-service/Dockerfile . -t ${{ env.REGISTRY }}/oauth-agent-service:latest
          docker push ${{ env.REGISTRY }}/oauth-agent-service:latest

          yarn nx build goal-service
          docker build -f apps/services/goal-service/Dockerfile . -t ${{ env.REGISTRY }}/goals-service:latest
          docker push ${{ env.REGISTRY }}/goals-service:latest
