name: Start AKS Cluster

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  start-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az aks start --name goalie --resource-group goalie
